### PR TITLE
Support single sign-on

### PR DESCRIPTION
**Pull request by mfenner**
## Purpose
Support authentication in DataCite Commons. This enables these functionalities:
* Personalization of the service. Initial version will have navigation link to DataCite Commons person page about the user, and navigation link to ORCID record.
* Enable beta testing. New features can be hidden in production using feature flags and made available to users logged in with `beta_tester` flag set in their account.
* Enable ORCID Search & Link claiming, duplicating the functionality available in DataCite Search

closes: #123

## Approach
Using the same single-sign on workflow as in DataCite Search. Authentication happens in Profiles service, a cookie that is visible in the domain is set using a JWT that contains information such as user name and user ORCID ID.

#### Open Questions and Pre-Merge TODOs
- [ ] There is an issue with the styling of the user menu. This might be a bug in the `react-bootstrap` library. Workaround for now is to use the same styling for sign-in button and user menu.
- [ ] Enable authentication headers in CORS settings for the GraphQL API. This will allow authenticated GraphQL requests from `akita` going forward.

## Learning
Explored the approaches to authentication for next.js, e.g. https://next-auth.js.org/. As authentication happens outside of the app, decided to write small session management component to implement authentication.

## Types of changes

- [ ] New feature (non-breaking change which adds functionality)

## Reviewer, please remember our [guidelines](https://datacite.atlassian.net/wiki/spaces/TEC/pages/1168375809/Pull+Request+Guidelines):

- Be humble in the language and feedback you give, ask don't tell.
- Consider using positive language as opposed to neutral when offering feedback. This is to avoid the negative bias that can occur with neutral language appearing negative.
- Offer suggestions on how to improve code e.g. simplification or expanding clarity.
- Ensure you give reasons for the changes you are proposing.
Bildschirmfoto 2020-09-06 um 08 11 39
Bildschirmfoto 2020-09-06 um 08 11 14

### CODE REVIEW

**Comment by kjgarza** [comment]
I was looking at it in stage and it seems that on login it send me to profiles. 

image

I would spec it would send me back to commons and show me logged but it doesn't do that.
image

**Comment by mfenner** [comment]
@kjgarza this is about correctly setting cookies between services. What you describe is the behaviour when you run both `akita` and `volpino` locally.

**Comment by mfenner** [comment]
I am investigating, but I think the issue is related to our separation of `test` and `stage` a few months ago, and `volpino` needing a fix.

**Comment by mfenner** [comment]
@kjgarza any feedback regarding the code?

**Pull request merged**
