### PR TITLE
Add PID Graph KPIs

### PR DESCRIPTION
**Pull request by mfenner**
## Purpose
With this pull request we are adding detailed PID Graph key performance indicators to DataCite Commons. This is a requirement from the FREYA grant.

closes: #135

## Approach
I have added a number of new pages, accessible via the new **Pages** menu. This includes a **General** page with overview stats of our data sources, pages for the major work types, people, organizations, and new PID types, such as data management plans or instruments.

#### Open Questions and Pre-Merge TODOs
<!--- - [ ] double-check that funding information is fetched correctly.

## Types of changes

- [ ] New feature (non-breaking change which adds functionality)

## Reviewer, please remember our [guidelines](https://datacite.atlassian.net/wiki/spaces/TEC/pages/1168375809/Pull+Request+Guidelines):

- Be humble in the language and feedback you give, ask don't tell.
- Consider using positive language as opposed to neutral when offering feedback. This is to avoid the negative bias that can occur with neutral language appearing negative.
- Offer suggestions on how to improve code e.g. simplification or expanding clarity.
- Ensure you give reasons for the changes you are proposing.

### CODE REVIEW

**Comment by mfenner** [comment]
Bildschirmfoto 2020-09-16 um 08 36 07

**Comment by mfenner** [comment]
Bildschirmfoto 2020-09-16 um 08 36 40

**Comment by mfenner** [comment]
Bildschirmfoto 2020-09-16 um 08 37 25

**Review by richardhallett — APPROVED** [review]
I ran locally and had a look at code, everything looks good.

**Pull request merged**
